version: '3'

services:
  odoo:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./custom_addons:/var/lib/odoo/custom_addons
      - odoo-filestore:/var/lib/odoo/filestore
      - odoo-data:/var/lib/odoo/data
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-odoo}
      - DB_PASSWORD=${DB_PASSWORD:-odoo}
      - PORT=${PORT:-8080}
      - CUSTOM_MODULES_BUCKET=${CUSTOM_MODULES_BUCKET:-odoo-custom-modules/custom_addons}
      - FILESTORE_BUCKET=${FILESTORE_BUCKET:-odoo-filestore-data}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

volumes:
  odoo-db-data:
  odoo-filestore:
  odoo-data: